# A Docker Compose must always start with the version tag.
# We use '3' because it's the last version.
version: '3'

networks:
  intranet:
    
volumes:
  kratos:

services:
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: contacts
      POSTGRES_PASSWORD: 90GPtnKUzQWEWlMockU4fJIPMM0EtbZf
      POSTGRES_DB: contacts_db
    networks:
        - intranet
  
  kratos-migrate:
    image: oryd/kratos:v1.0.0
    depends_on:
      - database
    environment:
      - DSN=postgres://contacts:90GPtnKUzQWEWlMockU4fJIPMM0EtbZf@database:5432/contacts_db?sslmode=disable&max_conns=20&max_idle_conns=4
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    volumes:
      - type: bind
        source: ./contrib/kratos
        target: /etc/config/kratos
    networks:
      - intranet
  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v1.0.0
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    restart: unless-stopped
    environment:
      - DSN=postgres://contacts:90GPtnKUzQWEWlMockU4fJIPMM0EtbZf@database:5432/contacts_db?sslmode=disable&max_conns=20&max_idle_conns=4
      - LOG_LEVEL=trace
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: bind
        source: ./contrib/kratos
        target: /etc/config/kratos
    networks:
      - intranet
  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'
    networks:
      - intranet